### PR TITLE
feat: add nv25 GST-skeleton

### PR DESCRIPTION
**Pull request by rjan90**
Ref: https://github.com/filecoin-project/go-state-types/issues/321

feat: add nv25 GST-skeleton

### CODE REVIEW

**Comment by masih** [comment]
How does one review 33K LOC 😱 

If this is a mechanical PR, I wonder if we should consider automating it.

**Comment by rjan90** [comment]
> If this is a mechanical PR, I wonder if we should consider automating it.

Yes, this is mostly a mechanical PR. It is just the steps outlined in 1. here: https://github.com/filecoin-project/lotus/blob/master/documentation/misc/Building_a_network_skeleton.md#go-state-types-checklist

**Comment by masih** [comment]
Thanks Captured this: https://github.com/filecoin-project/go-state-types/issues/326

**Review by masih — APPROVED** [review]
Seems OK. we need a machine to generate PRs like this as it is highly error prone to have humans create the PR _and_ humans reviewing it.

**Pull request merged**
